name: Lyla Tsiokos
favicon: null
layout_spectrum: 0.88745
typography_spectrum: 0.1024
title: "Lyla's Homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001f45'
    - '#33fafb'
    - '#02a1f5'
    - '#0277b7'
    - '#2cb9af'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
