name: Lyla Tsiokos
favicon: null
layout_spectrum: 0.19188
typography_spectrum: 0.1024
title: "Lyla's Homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a617e'
    - '#8e8fa3'
    - '#a2beed'
    - '#e4f7ed'
    - '#c9ae8e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
