name: Lyla Tsiokos
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03506
title: "Lyla's Homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a2341'
    - '#9e3144'
    - '#e2aeb0'
    - '#aa728f'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
