name: Lyla Tsiokos
favicon: null
layout_spectrum: 0.88745
typography_spectrum: 0.1024
title: "Lyla's Homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#66ccff'
    - '#ccffcc'
    - '#0099cc'
    - '#00339a'
    - '#4f7abd'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
