name: Lyla Tsiokos
favicon: null
layout_spectrum: 0.88745
typography_spectrum: 0.1024
title: "Lyla's Homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#513e14'
    - '#0acdbf'
    - '#cd2cd3'
    - '#2c7da3'
    - '#ffd2e8'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
